# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36acb04a606108fa8cdcfd48350989ba93d3b89a5da342afc9ac22de0f9fbaa3c2478566962ca658a39fa94688283dfc9e76f0298ba48faaa799101cc3a13343

test:
  secret_key_base: 0340d0d3b490058a45543226b70ddb68ce10b44ef342f3df71230d0bf5f86284cd8751b7929bf40ed66d7a5ae57a2dccd46e12d0e69f6760f684fb018f80667b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
